# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misLineas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/%d-%m-%Y'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
