# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misLineas', '0003_auto_20160618_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='para',
        ),
    ]
