# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misLineas', '0004_remove_contacto_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='medio',
            field=models.IntegerField(blank=True, choices=[(0, 'Seleccionar...'), (1, 'Rapipago'), (2, 'Pago facil'), (3, 'Link'), (4, 'Otros...')], default=0, null=True),
        ),
    ]
