# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misLineas', '0008_auto_20160619_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='abono',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='linea',
            name='plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
