# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misLineas', '0009_auto_20160619_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='alta',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='linea',
            name='plan',
            field=models.CharField(blank=True, choices=[('E', 'Economicoi $90'), ('M', 'Normal $150'), ('A', 'Premium $350')], max_length=1, null=True),
        ),
    ]
