# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misLineas', '0010_auto_20160619_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='plan',
            field=models.CharField(blank=True, choices=[('E', 'Economicoi $90'), ('M', 'Normal $150'), ('A', 'Premium $350')], default='E', max_length=1, null=True),
        ),
    ]
