# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misLineas', '0012_auto_20160619_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='contestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linea',
            name='plan',
            field=models.IntegerField(blank=True, choices=[(1, 'Economico $90'), (2, 'Normal $150'), (3, 'Premium $350')], default=1, null=True),
        ),
    ]
